apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bot-helper
  namespace: default
  labels:
    app:  bot-helper
spec:
  selector:
    matchLabels:
      app: bot-helper
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  bot-helper
    spec:
      volumes:
        - name: bot-helper-config
          configMap:
            name: errbotconfig
        - name: rclone-config
          secret:
            secretName: rcloneconfig
        - name: deploy-key-ssh
          secret:
            secretName: deploykeyssh
      containers:
      - name:  bot-helper
        image:  tritran14/bot-helper:COMMIT_ID
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - secretRef:
            name: bot-helper-creds
        volumeMounts:
          - name: bot-helper-config
            mountPath: /data/config.py
            subPath: config.py
          - name: rclone-config
            mountPath: /data/rclone.conf
            readOnly: true
            subPath: rclone.conf
          - name: deploy-key-ssh
            mountPath: /data/id_rsa_deploy
            readOnly: true
            subPath: id_rsa_deploy
      imagePullSecrets:
      - name: private-reg-cred
        
